# Generated by Django 5.0 on 2024-11-12 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crime_type', models.CharField(choices=[('Violent', 'Violent'), ('Financial', 'Financial'), ('Hate', 'Hate')], max_length=50)),
                ('sentence_length', models.PositiveIntegerField()),
                ('rehabilitated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('impact_level', models.IntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='cognify.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_run', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='cognify.criminal')),
            ],
        ),
    ]
