# Generated by Django 5.0 on 2024-11-12 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='date_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
