# Generated by Django 5.0 on 2024-11-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognify', '0003_criminal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='sentence_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
