# Generated by Django 5.0 on 2024-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognify', '0004_alter_criminal_sentence_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='rehabilitated',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='sentence_length',
        ),
        migrations.AddField(
            model_name='criminal',
            name='implanted_memories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='rehabilitation_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=50),
        ),
        migrations.AddField(
            model_name='criminal',
            name='rehabilitation_success_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='crime_type',
            field=models.CharField(max_length=50),
        ),
    ]
