# Generated by Django 5.0 on 2024-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognify', '0005_remove_criminal_rehabilitated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='crime_type',
            field=models.CharField(choices=[('Violent', 'Violent'), ('Financial', 'Financial'), ('Hate', 'Hate')], max_length=50),
        ),
    ]
